
comment: false

coverage:
  precision: 2
  round: down
  range: "70...100"


codecov:
  notify:
    # Prevent coverage status to upload multiple times for parallel and long
    # running CI pipelines. This configuration is particularly useful on PRs
    # to avoid confusion. Note that this value is set to the number of Azure
    # Pipeline jobs uploading coverage reports.
    after_n_builds: 1

ignore:
  - "./rlberry/rendering/opengl_render2d.py"
  - "./rlberry/rendering/pygame_render2d.py"
