
comment: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1% # allow coverage to drop at most 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "./rlberry/rendering/opengl_render2d.py"
  - "./rlberry/rendering/pygame_render2d.py"
  - "./rlberry/colab_utils/display_setup.py"
  - "./rlberry/agents/experimental/jax/**/*"
