
comment: false

codecov:
  require_ci_to_pass: yes
  notify:
    # Prevent coverage status to upload multiple times for parallel and long
    # running CI pipelines. This configuration is particularly useful on PRs
    # to avoid confusion. Note that this value is set to the number of Azure
    # Pipeline jobs uploading coverage reports.
    after_n_builds: 3

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1% # allow coverage to drop at most 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "./rlberry/rendering/opengl_render2d.py"
  - "./rlberry/rendering/pygame_render2d.py"
