import numpy as np
from rlberry.seeding.seeder import Seeder


_TORCH_INSTALLED = True
try:
    import torch
except Exception:
    _TORCH_INSTALLED = False


def set_external_seed(seeder):
    """
    Set seeds of external libraries.

    To do:
        Check (torch seeding):
        https://github.com/pytorch/pytorch/issues/7068#issuecomment-487907668

    Parameters
    ---------
    seeder: seeding.Seeder or int
        Integer or Seeder object from which to generate random seeds.
    """
    if np.issubdtype(type(seeder), np.integer):
        seeder = Seeder(seeder)

    # seed torch
    if _TORCH_INSTALLED:
        torch.manual_seed(seeder.seed_seq.generate_state(1, dtype=np.uint32)[0])


def safe_reseed(object, seeder):
    """
    Calls object.reseed(seed_seq) method if available;
    If a object.seed() method is available, call object.seed(seed_val),
    where seed_val is generated by the seeder.
    Otherwise, does nothing.

    Parameters
    ----------
    object : object
        Object to be reseeded.
    seeder: seeding.Seeder
        Seeder object from which to generate random seeds.

    Returns
    -------
    True if reseeding was done, False otherwise.
    """
    reseeded = False
    try:
        object.reseed(seeder)
        reseeded = True
    except AttributeError:
        seed_val = seeder.rng.integers(2**32).item()
        try:
            object.seed(seed_val)
            reseeded = True
        except AttributeError:
            reseeded = False

    # check if the object has observation and action spaces to be reseeded.
    try:
        safe_reseed(object.observation_space, seeder)
        safe_reseed(object.action_space, seeder)
    except AttributeError:
        pass

    return reseeded
