name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build:
        if: ${{ (github.event.label.name == 'ready for review') or (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
            azure-devops-project-url: https://dev.azure.com/timotheemathieu/timotheemathieu
            azure-pipeline-name: 'rlberry-py.rlberry'
